# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

as_table_with_rownames <- function(x) {
    .Call('_dbR6_as_table_with_rownames', PACKAGE = 'dbR6', x)
}

